using System;
using System.Diagnostics;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Windows.Forms;
using IronPython.Hosting;
using IronPython.Runtime;
using Microsoft.Scripting;
using Microsoft.Scripting.Hosting;

namespace Sales
{
    static class Program
    {

        /// <summary>
        /// The main entry point for the application.
        /// </summary>
        [STAThread]
        static void Main()
        {

            // This creates a form that prompts the user to select a directory
            //ASEN.ExperimentDialog formTest = new ASEN.ExperimentDialog();
            //Application.Run(formTest);
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = @"C:\Program Files (x86)\IronPython 2.7\ipy.exe";
            start.Arguments = @"C:\Users\sheph\Desktop\deploy\ASCOM.py";
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            var ourProcess = Process.Start(start);
            while (!ourProcess.StandardOutput.EndOfStream)
            {
                string line = ourProcess.StandardOutput.ReadLine();
                Console.WriteLine(line);
            }
            ourProcess.WaitForExit();
            Console.ReadLine();
        }
    }
}

